[package]
name = "torth-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
lazy_static = "1.4.0"
phf = { version = "0.11.1", features = ["macros"] }
regex = "1.7.1"
strum = "0.24.1"
strum_macros = "0.24.3"
